name: ApparelManagementApp
resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/ukdaga/spring-boot-sample-data-jpa-h2-master.git
      branch: master

jobs:
  - name: package
    plan:
    - get: git-repo
      trigger: true
    - task: package
      privileged: true
      file: git-repo/concourse-pipeline/package.yml
